version: "3.9"

services:
  mysql_todo_list_project:
    container_name: mysql_todo_list_project
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: db_todo_list
      MYSQL_PASSWORD: pass123
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ~/.MySQLDBData/mysql_todo_list_project
        target: /var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
